name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v5
    - uses: actions/cache@v1
      with:
       path: .m2/repository/
       key: ${{ github.ref }}
    - name: Build
      run: sbt -J-Xms2G -J-Xmx4G buildHttp4sTracer
