name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v5
    - name: Build
      run: sbt -J-Xms2G -J-Xmx4G buildHttp4sTracer
